[theme]
base = "dark"
primaryColor = "#A855F7"  # Tím gradient
backgroundColor = "#18181B"
secondaryBackgroundColor = "#27272A"
textColor = "#E4E4E7"
font = "sans serif"

[server]
maxUploadSize = 200
enableXsrfProtection = true