[theme]
base = "light"
primaryColor = "#1E88E5"  # Xanh dương chuyên nghiệp
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F7FA"
textColor = "#2C3E50"
font = "sans serif"

[server]
maxUploadSize = 200
enableXsrfProtection = true